# Site settings
baseurl: "" 

# One type of collection of posts, called "my_tags"
# Find in the the folder ./_my_tags
collections:
  my_tags:
    output: true
    permalink: /tag/:name/

# Color settings (Hex value without #)
color_alpha: feeaeb
color_beta: 05009e

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Instagram API
instagram_key: 
instagram_caption: true

# SEO settings
title: LambdaLisa
description: 
url: "http://lambdalisa.com"
email: "lisa.yc.huang@gmail.com"
twitter_username: "@bestcapetownSA"
default_img: 

# Profile settings
social:
  twitter: https://twitter.com/bestcapetownSA
  github: https://github.com/lisaychuang
  linkedin: https://www.linkedin.com/in/lisaychuang/

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-sitemap, octopress-autoprefixer, jekyll-paginate, jekyll-feed]


# For markdown files of type my_tags (found in ./my_tags)
# in all paths across the site (kind of like *.*)
# use "tag_index" as a default layout (./_layouts/tag_index.html)
# unless explicitly specified in the top metadata stuff
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag_index