# Site settings
title: Code for Spontaneity
header-img: img/home-bg.png
email: lisa.yc.huang@gmail.com
copyright_name: lisaychuang
description: > # this means to ignore newlines until "baseurl:"
  A journey into code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bestCapeTown
github_username:  lisaychuang
learn_profile: lisaychuang
email_username: lisa.yc.huang@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
